# Generated by Django 3.0.4 on 2020-03-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='content',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='publickey',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
