# Generated by Django 3.0.4 on 2020-04-09 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20200402_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkeys',
            name='id',
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
