# Generated by Django 3.0.4 on 2020-03-30 23:39

from django.db import migrations, transaction
from django.apps import apps
from django.contrib.auth.models import User
import datetime

def create_test_user(apps, schema_editor):
    user = User.objects.create_user('test', password='test', email="test@test.com", last_login=datetime.datetime.now())

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200330_2327'),
    ]

    operations = [
        migrations.RunPython(create_test_user),
    ]
