# Generated by Django 3.0.4 on 2020-04-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200402_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('messaging_key_id', models.CharField(max_length=100)),
                ('signing_key_id', models.CharField(max_length=100)),
            ],
        ),
    ]
