# Generated by Django 3.0.4 on 2020-04-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200402_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file_upload',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
