# Generated by Django 3.0.4 on 2020-04-10 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200409_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='messaging_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='messaging_key', to='app.PrivateKey'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='signing_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='signing_key', to='app.PrivateKey'),
        ),
    ]
