# Generated by Django 3.0.4 on 2020-04-02 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file_upload',
            new_name='file_to_decrypt',
        ),
    ]
