# Generated by Django 3.0.4 on 2020-04-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200410_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_private_key',
            field=models.FileField(upload_to=''),
        ),
    ]
