# Generated by Django 3.0.4 on 2020-04-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200402_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signed',
            field=models.BooleanField(default=False),
        ),
    ]
