# Generated by Django 3.0.4 on 2020-04-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PrivateKey'),
        ),
    ]
