# Generated by Django 3.0.4 on 2020-04-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200410_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.FileField(upload_to=''),
        ),
    ]
