# Generated by Django 3.0.4 on 2020-04-05 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_message_signing_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='secure_id',
            field=models.CharField(default='yeet', max_length=100),
            preserve_default=False,
        ),
    ]
