# Generated by Django 3.0.4 on 2020-04-10 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200410_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipient_private_key',
            new_name='recipient_public_key',
        ),
    ]
