# Generated by Django 3.0.4 on 2020-04-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20200405_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatekey',
            name='secure_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
