# Generated by Django 3.0.4 on 2020-04-08 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20200405_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaging_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_key', to='app.PrivateKey')),
                ('signing_key', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='signing_key', to='app.PrivateKey')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
