# Generated by Django 3.0.4 on 2020-04-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200411_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_key', to='app.PrivateKey'),
        ),
        migrations.AlterField(
            model_name='message',
            name='signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_key', to='app.PrivateKey'),
        ),
    ]
