# Generated by Django 3.0.4 on 2020-04-09 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_userkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkeys',
            name='messaging_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messaging_key', to='app.PrivateKey'),
        ),
        migrations.AlterField(
            model_name='userkeys',
            name='signing_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_key', to='app.PrivateKey'),
        ),
    ]
