# Generated by Django 3.0.4 on 2020-04-16 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200411_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recipient_public_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_key', to='app.UserKeys'),
        ),
    ]
