# Generated by Django 3.0.4 on 2020-04-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200416_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='signing_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sign_key', to='app.UserKeys'),
        ),
    ]
